## Config file
lr:              1e-4 # Initial learning rate
epochs:          50 # Number of epochs to train the model 
number_classes:  1 # Number of classes in the target dataset
batch_size_tr:   2 # Batch size for train
batch_size_va:   1 # Batch size for validationn 
saved_model:     './weights/weights_isic18.model' # leave '' will use a default value 
path_to_data:    '../yuli_version/processed_data/isic18/' #path to dataset
patience:        10 # number of epochs without improvement to do before finishing training early.
save_result:     './results/' # path to save results
progress_p:      0.1 # value between 0-1 shows the number of time we need to report training progress in each epoch
pretrained:      0 # load the previously trained weight or no value should either 1 or 0
